Algoritmo "consumo"

Var

 distanciaPercorrida :  inteiro
 combustivelGasto, consumoMedio : real


Inicio
       escreva ("Distância percorrida: " )
       leia (distanciaPercorrida)
       
       escreva ("Combustível gasto: " )
       leia (combustivelGasto)
       
       ConsumoMedio <- distanciaPercorrida / combustivelGasto
       
       escreval ("Consumo Médio = ", consumoMedio:4:3)




Fimalgoritmo