Algoritmo "teste_condicional_composta_duasPossibilidades"

Var

     hora : inteiro

Inicio

    escreva ("Digite uma hora do dia: " )
    leia (hora)
    
    se hora < 12 entao
       escreva ("Bom Dia!")
    senao
       se (hora >=12) e (hora<18) entao
         escreval ("Boa tarde!")
         
       senao
         escreval ("Boa noite!")
         
       fimse
    fimse
     
     
     



Fimalgoritmo
